version: '3'
services:
  frontend:
    stdin_open: true
    image: "${DOCKER_HUB_USERNAME}/theroom-frontend:latest"
    env_file:
      - .env
      - front.env
    ports:
      - "3000:3000"

  backend:
    image: "${DOCKER_HUB_USERNAME}/theroom-backend:latest"
    ports:
      - "8080:8080"
    env_file:
      - .env
      - back.env
    volumes:
      - /home/ec2-user/upload:/upload

  nginx:
    image: "${DOCKER_HUB_USERNAME}/theroom-nginx:latest"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt 
      - /var/lib/letsencrypt:/var/lib/letsencrypt 
    ports:
      - "80:80"
      - "433:433"