version: '3'
services:
  frontend:
    stdin_open: true
    image: "${DOCKER_HUB_USERNAME}/theroom-frontend:latest"
    env_file:
      - ./override.env
      - ./front.env
    ports:
      - "3000:3000"

  backend:
    image: "${DOCKER_HUB_USERNAME}/theroom-backend:latest"
    env_file:
      - ./override.env
      - ./back.env
    ports:
      - "8080:8080"
    environment:
      DB_URL: $DB_URL
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD

  nginx:
    image: "${DOCKER_HUB_USERNAME}/theroom-nginx:latest"
    env_file:
      - ./override.env
    ports:
      - "80:80"