version: '3'
services:
  frontend:
    stdin_open: true
    image: lano8080/theroom-frontend:latest
    ports:
      - "3000:3000"

  backend:
    image: lano8080/theroom-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - /home/ec2-user/upload:/upload

  nginx:
    image: lano8080/theroom-nginx:latest
    ports:
      - "80:80"