spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cicd-mysql.c5q4usykozou.ap-northeast-2.rds.amazonaws.com:3306/theroom
    username: root
    password: ghr42685

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
upload:
  path: /upload

account:
  username: theroom
  password: pass

allow:
  origin:
    path:
      main: http://ec2-3-39-137-110.ap-northeast-2.compute.amazonaws.com
      sub: http://ec2-3-39-137-110.ap-northeast-2.compute.amazonaws.com