spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        
upload:
  path: ${FILE_UPLOAD_PATH}

account:
  username: ${ACCOUNT_USERNAME}
  password: ${ACCOUNT_PASSWORD}

allow:
  origin:
    path:
      main: ${ORIGIN_MAIN}
      sub: ${ORIGIN_SUB}