name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

      # 3. Docker 이미지 remove
      - name: Remove old Docker image
        run: |
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-frontend:latest || true
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-backend:latest || true
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-nginx:latest || true

      # 4. Docker 이미지 build
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-backend:latest ./backend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-nginx:latest ./nginx

      # 5. Docker 이미지 push
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/theroom-nginx:latest

      # 6. docker-compose.yml, .env 파일 생성
      - name: Create docker-compose.yml and .env files
        run: |
          echo "${{ secrets.DOCKER_COMPOSE_YML_BASE64_ENCODE }}" | base64 -d > docker-compose.yml
          echo "${{ secrets.FRONT_ENV }}" > front.env
          echo "${{ secrets.BACK_ENV }}" > back.env
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > override.env
    
      # 7. 파일 전송 (scp) - docker-compose.yml, .env ec2에 전송
      - name: Upload Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "docker-compose.yml,front.env,back.env,override.env"
          target: "~/app"

      # 8. EC2에서 컨테이너 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/app
            docker-compose down
            docker-compose pull
            docker-compose up -d